# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='family',
            field=models.CharField(choices=[('red', 'RED'), ('blue', 'BLUE'), ('brown', 'BROWN'), ('yellow', 'YELLOW'), ('orange', 'ORANGE')], default='random', max_length=10),
        ),
    ]
