# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play1', '0004_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='players',
            field=models.IntegerField(default=5),
        ),
    ]
