# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wish.Profile'),
        ),
    ]
