# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santa_ver_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='lists',
        ),
    ]
