# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santa_ver_1', '0002_remove_member_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lists', models.ManyToManyField(to='santa_ver_1.List')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='member_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='santa_ver_1.List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list_member',
            name='members',
            field=models.ManyToManyField(to='santa_ver_1.Member'),
        ),
    ]
