# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 06:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_ver_1', '0003_auto_20171210_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='gift_max',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1, message='Cannot be less than 1 dollar'), django.core.validators.MaxValueValidator(1000, message='Cannot be more than 1000 dollars')]),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='update name', max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='Cannot be blank'), django.core.validators.MaxLengthValidator(255, message='Cannot be more than 100 charaters')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default='unknown', max_length=200, validators=[django.core.validators.MinLengthValidator(1, message='Cannot be blank'), django.core.validators.MaxLengthValidator(100, message='Cannot be more than 100 charaters')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='Cannot be blank'), django.core.validators.MaxLengthValidator(255, message='Cannot be more than 100 charaters')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.BigIntegerField(default=1234567890, validators=[django.core.validators.MinLengthValidator(9, message='Must be 10 characters'), django.core.validators.MaxLengthValidator(10, message='Must be 10 characters')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alias',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='Cannot be blank'), django.core.validators.MaxLengthValidator(100, message='Cannot be more than 100 charaters')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1, message='Cannot be blank'), django.core.validators.MaxLengthValidator(100, message='Cannot be more than 100 charaters'), django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Cannot be blank'), django.core.validators.MaxLengthValidator(100, message='Cannot be more than 100 charaters')]),
        ),
    ]
