# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_ver_1', '0004_auto_20171217_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='gift_max',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='update name', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alias',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
