# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='dbz.User'),
            preserve_default=False,
        ),
    ]
