# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbz', '0004_auto_20171120_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DSSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='DSSN',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='dbz.DSSN'),
        ),
    ]
