# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='secret_santa.BaseModel')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.BigIntegerField(default=1234567890)),
            ],
            bases=('secret_santa.basemodel',),
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='update name', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='lists',
            field=models.ManyToManyField(to='secret_santa.List'),
        ),
    ]
