# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0002_auto_20171207_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
