# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0003_auto_20171207_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
