# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='add dob', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='random_username', max_length=200),
        ),
    ]
