# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0002_auto_20171126_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke_Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(default='random_alias', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='random_email', max_length=200),
        ),
        migrations.AddField(
            model_name='poke_attempt',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_pokes', to='pokes.User'),
        ),
        migrations.AddField(
            model_name='poke_attempt',
            name='user_poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='pokes.User'),
        ),
    ]
