# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0003_auto_20171126_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke_attempt',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_attempts', to='pokes.User'),
        ),
    ]
