# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_dojos_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='color',
            field=models.CharField(default='red', max_length=100),
        ),
    ]
