# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_ninjas_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='day',
            field=models.CharField(default='Monday', max_length=50),
            preserve_default=False,
        ),
    ]
