# Generated by Django 2.0.1 on 2018-02-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostVote',
        ),
    ]
